In [7]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [8]:
import torch

In [9]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones([3,4,5])

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [11]:
torch.Tensor([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [12]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [13]:
x.size()

torch.Size([3, 4])

In [14]:
x.shape

torch.Size([3, 4])

In [15]:
x[0]

tensor([1., 2., 3., 4.])

In [16]:
x[1]

tensor([5., 6., 7., 8.])

In [17]:
x[0,0]

tensor(1.)

In [18]:
x[:,0]

tensor([1., 5., 9.])

In [19]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [20]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [21]:
y = torch.Tensor([[12, 11, 10, 9],
                 [8, 7, 6, 5],
                 [4, 3, 2, 1]])

In [22]:
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [23]:
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [24]:
x % 2

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.]])

In [25]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [26]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [27]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

# использование масок

In [28]:
mask = x > 3

In [29]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [30]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [31]:
x.sum

<function Tensor.sum>

In [32]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = x[x > limit].sum()

print(larger_than_limit_sum)

4
tensor(35)


# копирование тензоров

In [33]:
y = x
y[0, 0] = 999
print(x)
print(y)#происходит копирование по ссылке, все дублируется впоследствии

tensor([[999,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]])
tensor([[999,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]])


In [34]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [35]:
y = x.clone()#обычное копирование
y[0,0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


# меняем тип данных и точность

In [36]:
x.dtype

torch.float32

In [37]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


# использование библиотеки numpy

In [38]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [39]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [40]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

# Вычисления на GPU


In [55]:
x = torch.rand([2000, 3000])
x

tensor([[0.4305, 0.3993, 0.2326,  ..., 0.7191, 0.3112, 0.9077],
        [0.8903, 0.4041, 0.0271,  ..., 0.0913, 0.8481, 0.9561],
        [0.5330, 0.3620, 0.0725,  ..., 0.0640, 0.4692, 0.9401],
        ...,
        [0.2297, 0.6976, 0.3942,  ..., 0.1403, 0.2775, 0.1384],
        [0.2371, 0.8435, 0.2498,  ..., 0.3877, 0.9332, 0.7669],
        [0.0102, 0.7694, 0.8044,  ..., 0.7857, 0.4146, 0.6365]])

In [43]:
torch.cuda.is_available()

True

In [44]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [45]:
torch.device('cpu')

device(type='cpu')

In [52]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [51]:
x_cuda = x.to(device)
x_cuda

tensor([[0.2766, 0.6533, 0.6768],
        [0.7129, 0.0262, 0.8906]], device='cuda:0')

In [56]:
%time y = (x - x + x * 10.0)**2

CPU times: user 14.8 ms, sys: 44.3 ms, total: 59 ms
Wall time: 59.3 ms


In [57]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0)**2

CPU times: user 0 ns, sys: 265 µs, total: 265 µs
Wall time: 271 µs
